# Desafio: trabajando en otros contextos

Proyecto Desafío 1: Ventas Online - dados_vendas_clientes.json  
Proyecto Desafío 2: Administración de Condominios - dados_locacao_imoveis.json.

## Etapa 1

* Proyecto Desafio 1: Ventas Online  
el desafío del proyecto 1: ventas online será abrir la base de datos con Pandas y aplicar json_normalize.

In [1]:
import pandas as pd

In [49]:
datos = pd.read_json('practica/dados_vendas_clientes.json')

In [3]:
datos

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [50]:
#aplicando normalize
datos_normalizados = pd.json_normalize(datos['dados_vendas'])

In [51]:
datos_normalizados

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

* Proyecto Desafío 2: Administración de Condominios  
el desafío del proyecto 2: administración del condominio será similar al desafío del proyecto 1, abrir la base de datos con Pandas y aplicar json_normalize al DataFrame.

In [45]:
datos2 = pd.read_json('practica/dados_locacao_imoveis.json')

In [7]:
datos2

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [57]:
#aplicando normalizacion a datos2
datos2_normalizados = pd.json_normalize(datos2['dados_locacao'])

In [58]:
datos2_normalizados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

## Etapa 2

* Proyecto Desafío 1: Ventas Online  
Leímos la base de datos en el desafío anterior, ahora podemos seguir adelante con la transformación de estos datos. Así, el nuevo desafío del proyecto 1 será dividido en algunas metas:

- Eliminar datos en listas dentro del DataFrame;
- Verificar tipos de datos;
- Identificar columnas numéricas;
- Transformar la columna numérica a tipo numérico.

In [10]:
#datos_normalizados son los datos de la etapa 1 de ventas online
datos_normalizados.head(3)

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"

In [11]:
columnas = list(datos_normalizados)
columnas

['Data de venda', 'Cliente', 'Valor da compra']

In [59]:
# ------------- aplico metodo explode a partir de la 2 columna -------------
datos = datos_normalizados.explode(columnas[1:])
datos

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [13]:
# ------------- resetear indices -------------
datos.reset_index(drop=True, inplace=True)
datos.head(3)

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8

In [14]:
# ------------- verificar tipos de datos -------------
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [15]:
# ------------- ransformar la columna numérica a tipo numérico -------------
import numpy as np

In [16]:
# antes de transformar columna valor de compra de object a float, elimino R$,(coma),espacios
datos['Valor da compra'] = datos['Valor da compra'].apply(lambda x: x.replace('R$', '').replace(',', '').strip())

In [17]:
datos['Valor da compra'] = datos['Valor da compra'].astype(np.float64)

In [18]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

* Proyecto Desafío 2: Administración de Condominios  
Leímos la base de datos en el desafío anterior, ahora podemos seguir adelante con la transformación de estos datos. Entonces, de la misma manera que en el proyecto 1, el desafío del proyecto 2 está listado en algunas metas:

- Eliminar datos en listas dentro del DataFrame;
- Verificar tipos de datos;
- Identificar columnas numéricas;
- Transformar la columna numérica a tipo numérico.

In [83]:
#datos del json administracion de condominios
datos2_normalizados.head(3)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"

In [84]:
# ------------- obtener el nombre de las columnas -------------
columnas2 = list(datos2_normalizados)
columnas2

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [85]:
# ------------- desglozar las columnas a partir a la segunda -------------
datos2 = datos2_normalizados.explode(columnas2[1:])

In [86]:
datos2.head(3)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"

In [87]:
# ------------- resetear indices -------------
datos2.reset_index(drop=True, inplace=True)
datos2.head(3)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"

In [88]:
# ------------- Transformar la columna numérica a tipo numérico. -------------
import numpy as np

In [89]:
datos2['valor_aluguel'] = datos2['valor_aluguel'].apply(lambda x: x.replace('$', '').replace('reais', '').replace(',', '').strip())

In [90]:
datos2.head(3)

      apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         10000
1  A101 (blocoAP)                 01/07/2022         03/07/2022         25000
2  A102 (blocoAP)                 02/06/2022         02/06/2022         11000

In [91]:
datos2['valor_aluguel'] = datos2['valor_aluguel'].astype(np.float64)

In [92]:
datos2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

## Etapa 3

* Proyecto Desafío 1: Ventas Online  
Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto resultó en una columna de nombres de clientes con una combinación de letras, mayúsculas y minúsculas, números y otros caracteres.  

Sabiendo esto, manipula los textos de la columna *Cliente* para que el resultado sean los nombres de los clientes en letras minúsculas, con ausencia de caracteres especiales o números.

In [60]:
datos.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31

In [61]:
datos['Cliente']

0       @ANA _LUCIA 321
0    DieGO ARMANDIU 210
0    DieGO ARMANDIU 210
0    DieGO ARMANDIU 210
1    Isabely JOanes 738
1    Isabely JOanes 738
1    Isabely JOanes 738
1    Isabely JOanes 738
2    Isabely JOanes 738
2      JOãO Gabriel 671
2    Julya meireles 914
2    Julya meireles 914
3    Julya meireles 914
3       MaRIA Julia 444
3       MaRIA Julia 444
3       MaRIA Julia 444
4       MaRIA Julia 444
4       PEDRO PASCO 812
4      Paulo castro 481
4     Thiago fritzz 883
Name: Cliente, dtype: object

In [ ]:
#minuscula
datos['Cliente'] = datos['Cliente'].str.lower()

In [80]:
#eliminar caracteres especiales o numeros
#datos['Cliente'].str.replace('[^a-z ]', ' ', regex=True)#problema: elimina caracter acentuado
#mantiene minus, acentuados, espacios en blanco y elimina todas las ocurrencias no solo la primera
datos['Cliente'] = (
    datos['Cliente']
    .str.normalize('NFKD') #separar acentos
    .str.encode('ascii', errors='ignore') #elimina acentos
    .str.decode('utf-8')
    .str.replace(r'[^a-zA-Z ]', ' ', regex=True) #eliminar numeros y simbolos
    .str.lower()
    .str.replace(r'\\s+', ' ', regex=True) #convertir espacios multiples en uno solo
    .str.strip()
)
datos['Cliente']

0        ana  lucia
0    diego armandiu
0    diego armandiu
0    diego armandiu
1    isabely joanes
1    isabely joanes
1    isabely joanes
1    isabely joanes
2    isabely joanes
2      joao gabriel
2    julya meireles
2    julya meireles
3    julya meireles
3       maria julia
3       maria julia
3       maria julia
4       maria julia
4       pedro pasco
4      paulo castro
4     thiago fritzz
Name: Cliente, dtype: object

* Proyecto Desafío 2: Administración de Condominios  
Buscando explicar la organización de la identificación de los apartamentos, durante la creación del conjunto de datos se añadió el texto *(blocoAP)*. Este texto informa que los nombres de los apartamentos están organizados con la letra mayúscula seguida del número del apartamento. Sin embargo, esto no aporta ninguna información a nuestros datos, por lo que resulta interesante eliminar este texto del conjunto de datos.

Con esto, manipule los textos de la columna *apartamento* para eliminar el texto *(blocoAP)* del DataFrame.

In [93]:
datos2.head()

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022        10000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022        25000.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022        11000.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022        26000.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022        12000.0

In [99]:
datos2['apartamento'].head()

0    A101
1    A101
2    A102
3    A102
4    B201
Name: apartamento, dtype: object

In [98]:
datos2['apartamento'] = datos2['apartamento'].str.replace(r'\(.*?\)', ' ', regex=True).str.strip()

## Etapa 4